# Name: [Progress, quality, durability, progress difficulty, quality difficulty, extra progress difficulty, extra quality difficulty]
# as can be found on other solver websites, such as https://yyyy.games/crafter/index.html#/simulator and checking custom recipe.
# The language option is the second menu to the left from the top-right hand corner.
# If this seems super convoluted, and you'd rather it was just the three in-game values, know that me too.
# Unfortunately that is how the craft system works in FFXIV.

Lvl88: [1650, 7000, 40, 128, 112, 100, 100]
Patch6.3_precrafts: [3696, 8200, 35, 130, 115, 80, 70]
Patch6.3_gear: [5060, 12628, 70, 130, 115, 80, 70]
Patch6.3_gatherer: [5720, 12900, 70, 130, 115, 80, 70]
Patch6.4_precrafts: [4488, 9090, 35, 130, 115, 80, 70]
Patch6.4_gear: [6600, 14040, 70, 130, 115, 80, 70]