# Name: [Craftsmanship, control, cp]
# You are encouraged to use this either for multiple characters if you have them, or different jobs having
# different gear or melds.
# The top line will always be selected by default         


Vicky Crosia: [4021, 3933, 587]
Dandaedre Zadiel: [0, 0, 2]
Sekundes Dullahan: [2566, 2443, 522]
ewww: [213, 3124, 0]
bernard: [0, 0, 0]
