# Name: [Craftsmanship, control, cp]
# You are encouraged to use this either for multiple characters if you have them, or different jobs having
# different gear or melds.
# The top line will always be selected by default         


Vicky Crosia: [4021, 3987, 601]
Ladisla Kociann: [4021, 3951, 580]